"""inital Migration

Revision ID: 4b09311bfa06
Revises: 
Create Date: 2025-07-08 18:03:52.876739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b09311bfa06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('fitness_level', sa.String(length=50), nullable=True),
    sa.Column('exercise_availability', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('push_ups', sa.Integer(), nullable=True),
    sa.Column('sit_ups', sa.Integer(), nullable=True),
    sa.Column('squats', sa.Integer(), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('half_mile_time', sa.Float(), nullable=True),
    sa.Column('shoulders', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('biceps', sa.Float(), nullable=True),
    sa.Column('forearms', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('hips', sa.Float(), nullable=True),
    sa.Column('thighs', sa.Float(), nullable=True),
    sa.Column('calves', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
